[tool.poetry]
name = 'lexicon_collect'
version = '0.1.0'
description = 'Simple commandline and lib toolset for word definitions from Merriam Webster and Oxford dictionaries'
authors = ['roboto84 <7658704+roboto84@users.noreply.github.com>']

[tool.poetry.dependencies]
python = '^3.8'
requests = '^2.25.0'
python-dotenv = '^0.15.0'

[tool.poetry.dev-dependencies]
pytest = '^5.2'

[build-system]
requires = ['poetry-core>=1.0.0']
build-backend = 'poetry.core.masonry.api'
